In [1]:
import pandas as pd
import numpy as np

In [2]:
desc = pd.read_csv('description.csv', sep=';', encoding='1251', index_col=0)
desc

,Наименование поля,Описание поля,Описание значений
№,,,
1,DATA_TYPE,Тип выборки,TRAIN - обучающая выборка\nTEST - тестовая выб...
2,POLICY_ID,ID полиса,NaN
3,POLICY_BEGIN_MONTH,Месяц начала действия полиса,NaN
4,POLICY_END_MONTH,Месяц окончания действия полиса,NaN
5,POLICY_IS_RENEWED,Факт пролонгации полиса. Прогнозируемый параметр,Для тестовой выборки параметр обнулён
6,POLICY_SALES_CHANNEL,Канал продаж полиса,NaN
7,POLICY_SALES_CHANNEL_GROUP,Группа каналов продаж (группировка для колонки...,NaN
8,POLICY_BRANCH,Филиал продажи полиса,NaN
9,POLICY_MIN_AGE,Минимальный возраст лиц допущенных к управлени...,NaN
10,POLICY_MIN_DRIVING_EXPERIENCE,Минимальный стаж вождения лиц допущенных к упр...,NaN
11,VEHICLE_MAKE,Марка ТС,NaN
12,VEHICLE_MODEL,Модель ТС,NaN
13,VEHICLE_ENGINE_POWER,Мощность двигателя ТС,Мощность в лошадиных силах
14,VEHICLE_IN_CREDIT,ТС куплено в кредит,NaN
15,VEHICLE_SUM_INSURED,Страховая сумма по полису (оценочная стоимость...,NaN
16,POLICY_INTERMEDIARY,Посредник по полису,Идентификатор посредника
17,INSURER_GENDER,Пол страхователя,M - мужчина\nF - женщина
18,POLICY_CLM_N,"Кол-во убытков, всего по данному полису",Цифра - количество убытков.\nДля клиентов с од...
19,POLICY_CLM_GLT_N,"Кол-во убытков, где клиент виновен в ДТП по да...",NaN
20,POLICY_PRV_CLM_N,"Кол-во убытков, всего по предыдущему (если ест...",NaN
21,POLICY_PRV_CLM_GLT_N,"Кол-во убытков, где клиент виновен в ДТП по пр...",NaN
22,CLIENT_HAS_DAGO,У клиента также есть полис ДАГО (ДАГО - расшир...,NaN
23,CLIENT_HAS_OSAGO,У клиента также есть полис ОСАГО,NaN
24,POLICY_COURT_SIGN,По полису был суд,NaN
25,CLAIM_AVG_ACC_ST_PRD,Среднее время от страхового случая до заявлени...,NaN
26,POLICY_HAS_COMPLAINTS,По полису были жалобы (в том числе при урегули...,NaN
27,POLICY_YEARS_RENEWED_N,Количество лет пролонгации полиса,NaN
28,POLICY_DEDUCT_VALUE,Сумма франшизы по полису,NaN
29,CLIENT_REGISTRATION_REGION,Регион регистрации страхователя,"Регион, где клиент зарегистрирован по паспорту"
30,POLICY_PRICE_CHANGE,"Как поменялась премия при пролонгации \n(""цена...","Изменения в %, если > 0, то значит, что цена в..."

In [3]:
data = pd.read_csv('data.txt', sep=';')
data.head()

,DATA_TYPE,POLICY_ID,POLICY_BEGIN_MONTH,POLICY_END_MONTH,POLICY_IS_RENEWED,POLICY_SALES_CHANNEL,POLICY_SALES_CHANNEL_GROUP,POLICY_BRANCH,POLICY_MIN_AGE,POLICY_MIN_DRIVING_EXPERIENCE,...,POLICY_PRV_CLM_GLT_N,CLIENT_HAS_DAGO,CLIENT_HAS_OSAGO,POLICY_COURT_SIGN,CLAIM_AVG_ACC_ST_PRD,POLICY_HAS_COMPLAINTS,POLICY_YEARS_RENEWED_N,POLICY_DEDUCT_VALUE,CLIENT_REGISTRATION_REGION,POLICY_PRICE_CHANGE
0,TRAIN,1,1,1,1,39,1,Москва,51,12,...,N,1,0,0,0.0,0,0,0.0,Тульская,-1.00
1,TRAIN,2,1,1,1,50,5,Москва,35,7,...,0,1,1,0,0.0,0,4,0.0,Москва,-0.05
2,TRAIN,3,1,1,1,52,6,Москва,41,6,...,1L,0,0,0,0.0,0,1,12518.0,Московская,-0.07
3,TRAIN,4,1,1,1,50,5,Москва,36,12,...,0,1,1,0,0.0,0,6,15000.0,Москва,0.05
4,TRAIN,5,1,1,0,52,6,Санкт-Петербург,42,5,...,N,0,0,0,0.0,0,0,50000.0,Ленинградская,0.17

In [4]:
# variable for pre-modeling
df = data.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96605 entries, 0 to 96604
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   DATA_TYPE                      96605 non-null  object
 1   POLICY_ID                      96605 non-null  int64
 2   POLICY_BEGIN_MONTH             96605 non-null  int64
 3   POLICY_END_MONTH               96605 non-null  int64
 4   POLICY_IS_RENEWED              96605 non-null  int64
 5   POLICY_SALES_CHANNEL           96605 non-null  int64
 6   POLICY_SALES_CHANNEL_GROUP     96605 non-null  int64
 7   POLICY_BRANCH                  96605 non-null  object
 8   POLICY_MIN_AGE                 96605 non-null  int64
 9   POLICY_MIN_DRIVING_EXPERIENCE  96605 non-null  int64
 10  VEHICLE_MAKE                   96605 non-null  object
 11  VEHICLE_MODEL                  96605 non-null  object
 12  VEHICLE_ENGINE_POWER           96605 non-null  float64
 13  VEHICLE_IN_CREDIT              96605 non-null  int64
 14  VEHICLE_SUM_INSURED            96605 non-null  float64
 15  POLICY_INTERMEDIARY            96605 non-null  object
 16  INSURER_GENDER                 96605 non-null  object
 17  POLICY_CLM_N                   96605 non-null  object
 18  POLICY_CLM_GLT_N               96605 non-null  object
 19  POLICY_PRV_CLM_N               96605 non-null  object
 20  POLICY_PRV_CLM_GLT_N           96605 non-null  object
 21  CLIENT_HAS_DAGO                96605 non-null  int64
 22  CLIENT_HAS_OSAGO               96605 non-null  int64
 23  POLICY_COURT_SIGN              96605 non-null  int64
 24  CLAIM_AVG_ACC_ST_PRD           96605 non-null  float64
 25  POLICY_HAS_COMPLAINTS          96605 non-null  int64
 26  POLICY_YEARS_RENEWED_N         96605 non-null  object
 27  POLICY_DEDUCT_VALUE            96605 non-null  float64
 28  CLIENT_REGISTRATION_REGION     96605 non-null  object
 29  POLICY_PRICE_CHANGE            96605 non-null  float64
dtypes: float64(5), int64(13), object(12)
memory usage: 22.1+ MB

In [5]:
for col_name in df.columns:
    if df[col_name].dtypes == 'object':
        n_unique = len(df[col_name].unique())
        print(f"Feature '{col_name}' has {n_unique} unique categories")

Feature 'DATA_TYPE' has 2 unique categories
Feature 'POLICY_BRANCH' has 2 unique categories
Feature 'VEHICLE_MAKE' has 83 unique categories
Feature 'VEHICLE_MODEL' has 549 unique categories
Feature 'POLICY_INTERMEDIARY' has 1406 unique categories
Feature 'INSURER_GENDER' has 2 unique categories
Feature 'POLICY_CLM_N' has 7 unique categories
Feature 'POLICY_CLM_GLT_N' has 7 unique categories
Feature 'POLICY_PRV_CLM_N' has 7 unique categories
Feature 'POLICY_PRV_CLM_GLT_N' has 7 unique categories
Feature 'POLICY_YEARS_RENEWED_N' has 12 unique categories
Feature 'CLIENT_REGISTRATION_REGION' has 85 unique categories

In [6]:
# devide CLIENT_REGISTRATION_REGION in 6 groups: Санкт-Петербург, Москва, Московская, Ленинградская, Other
print(df['CLIENT_REGISTRATION_REGION'].value_counts().sort_values(ascending=False).head(10))

Санкт-Петербург    38854
Москва             34420
Московская         12820
Ленинградская       5877
N                   1130
Калужская            275
Тульская             219
Тверская             205
Владимирская         172
Новгородская         138
Name: CLIENT_REGISTRATION_REGION, dtype: int64

In [7]:
df['CLIENT_REGISTRATION_REGION'] = [x if x in ['Санкт-Петербург', 'Москва', 'Московская', 'Ленинградская'] else 'Other' for x in df['CLIENT_REGISTRATION_REGION']]
df['CLIENT_REGISTRATION_REGION'].value_counts()

Санкт-Петербург    38854
Москва             34420
Московская         12820
Ленинградская       5877
Other               4634
Name: CLIENT_REGISTRATION_REGION, dtype: int64

In [8]:
# devide POLICY_SALES_CHANNEL in groups with more than 500 policies and Other
channel_count = df['POLICY_SALES_CHANNEL'].value_counts()
print(channel_count.sort_values(ascending=False).head(15))

52    24728
53    21070
50    16176
55    11397
54     4897
59     2923
10     2332
6      1093
1       974
13      867
14      747
15      735
8       676
4       579
60      570
Name: POLICY_SALES_CHANNEL, dtype: int64

In [9]:
df['POLICY_SALES_CHANNEL'] = [x if channel_count[x] > 500 else 'Other' for x in df['POLICY_SALES_CHANNEL']]
df['POLICY_SALES_CHANNEL'].value_counts()

52       24728
53       21070
50       16176
55       11397
Other     6841
54        4897
59        2923
10        2332
6         1093
1          974
13         867
14         747
15         735
8          676
4          579
60         570
Name: POLICY_SALES_CHANNEL, dtype: int64

In [10]:
# devide VEHICLE_MAKE in groups with more than 100 cars and Other
make_count = df['VEHICLE_MAKE'].value_counts()
print(make_count.sort_values().head())

МАЗ        1
<Пусто>    1
Iveco      1
Hafei      1
Krone      1
Name: VEHICLE_MAKE, dtype: int64

In [11]:
df['VEHICLE_MAKE'] = [x if make_count[x] > 100 else 'Other' for x in df['VEHICLE_MAKE']]

In [12]:
# devide VEHICLE_MODEL in groups with more than 100 cars and Other
model_count = df['VEHICLE_MODEL'].value_counts()
print(model_count.sort_values())

3302                  1
ATS                   1
2109                  1
Discovery Sport       1
147                   1
                   ...
ix35               2971
Focus              3196
Duster             3612
Sportage           3692
RAV4               4186
Name: VEHICLE_MODEL, Length: 549, dtype: int64

In [13]:
df['VEHICLE_MODEL'] = [x if model_count[x] > 30 else 'Other' for x in df['VEHICLE_MODEL']]

In [14]:
df['VEHICLE_MODEL'].value_counts(ascending=False)

RAV4              4186
Sportage          3692
Duster            3612
Focus             3196
ix35              2971
                  ...
5-series GT         31
Edge                31
Jazz                31
217130 Priora       31
Grand Santa Fe      31
Name: VEHICLE_MODEL, Length: 233, dtype: int64

In [15]:
group_count = df['POLICY_SALES_CHANNEL_GROUP'].value_counts()
print(group_count)

6    62093
5    16176
1     9860
4     4211
3     3621
8      420
2      200
7       24
Name: POLICY_SALES_CHANNEL_GROUP, dtype: int64

In [16]:

df['POLICY_SALES_CHANNEL_GROUP'] = [x if group_count[x] > 3000 else 'Other' for x in df['POLICY_SALES_CHANNEL_GROUP']]
df['POLICY_SALES_CHANNEL_GROUP'].value_counts()

6        62093
5        16176
1         9860
4         4211
3         3621
Other      644
Name: POLICY_SALES_CHANNEL_GROUP, dtype: int64

In [17]:
# looking for cat features
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96605 entries, 0 to 96604
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   DATA_TYPE                      96605 non-null  object
 1   POLICY_ID                      96605 non-null  int64
 2   POLICY_BEGIN_MONTH             96605 non-null  int64
 3   POLICY_END_MONTH               96605 non-null  int64
 4   POLICY_IS_RENEWED              96605 non-null  int64
 5   POLICY_SALES_CHANNEL           96605 non-null  object
 6   POLICY_SALES_CHANNEL_GROUP     96605 non-null  object
 7   POLICY_BRANCH                  96605 non-null  object
 8   POLICY_MIN_AGE                 96605 non-null  int64
 9   POLICY_MIN_DRIVING_EXPERIENCE  96605 non-null  int64
 10  VEHICLE_MAKE                   96605 non-null  object
 11  VEHICLE_MODEL                  96605 non-null  object
 12  VEHICLE_ENGINE_POWER           96605 non-null  float64
 13  VEHICLE_IN_CREDIT              96605 non-null  int64
 14  VEHICLE_SUM_INSURED            96605 non-null  float64
 15  POLICY_INTERMEDIARY            96605 non-null  object
 16  INSURER_GENDER                 96605 non-null  object
 17  POLICY_CLM_N                   96605 non-null  object
 18  POLICY_CLM_GLT_N               96605 non-null  object
 19  POLICY_PRV_CLM_N               96605 non-null  object
 20  POLICY_PRV_CLM_GLT_N           96605 non-null  object
 21  CLIENT_HAS_DAGO                96605 non-null  int64
 22  CLIENT_HAS_OSAGO               96605 non-null  int64
 23  POLICY_COURT_SIGN              96605 non-null  int64
 24  CLAIM_AVG_ACC_ST_PRD           96605 non-null  float64
 25  POLICY_HAS_COMPLAINTS          96605 non-null  int64
 26  POLICY_YEARS_RENEWED_N         96605 non-null  object
 27  POLICY_DEDUCT_VALUE            96605 non-null  float64
 28  CLIENT_REGISTRATION_REGION     96605 non-null  object
 29  POLICY_PRICE_CHANGE            96605 non-null  float64
dtypes: float64(5), int64(11), object(14)
memory usage: 22.1+ MB

In [18]:
for_encoding = ['POLICY_SALES_CHANNEL', 'POLICY_SALES_CHANNEL_GROUP', 'POLICY_BRANCH', 'VEHICLE_MAKE', 'VEHICLE_MODEL', 'INSURER_GENDER', 'POLICY_CLM_N',
'POLICY_CLM_GLT_N', 'POLICY_PRV_CLM_N', 'POLICY_PRV_CLM_GLT_N', 'CLIENT_REGISTRATION_REGION']

# outliers in: POLICY_MIN_DRIVING_EXPERIENCE (2015 years), VEHICLE_ENGINE_POWER (2000hp), VEHICLE_SUM_INSURED (0rub)
df[df.columns[~df.columns.isin(for_encoding)]].describe()

,POLICY_ID,POLICY_BEGIN_MONTH,POLICY_END_MONTH,POLICY_IS_RENEWED,POLICY_MIN_AGE,POLICY_MIN_DRIVING_EXPERIENCE,VEHICLE_ENGINE_POWER,VEHICLE_IN_CREDIT,VEHICLE_SUM_INSURED,CLIENT_HAS_DAGO,CLIENT_HAS_OSAGO,POLICY_COURT_SIGN,CLAIM_AVG_ACC_ST_PRD,POLICY_HAS_COMPLAINTS,POLICY_DEDUCT_VALUE,POLICY_PRICE_CHANGE
count,96605.000000,96605.000000,96605.000000,96605.000000,96605.000000,96605.000000,96605.000000,96605.000000,9.660500e+04,96605.000000,96605.000000,96605.000000,96605.000000,96605.000000,96605.000000,96605.000000
mean,48303.000000,6.891393,6.870400,0.500761,42.580767,34.910357,154.195851,0.321950,9.806700e+05,0.277480,0.550303,0.001014,3.877110,0.007660,5974.134461,-0.033025
std,27887.605715,3.400597,3.403665,0.500002,10.694670,199.928966,54.117543,0.467226,6.900919e+05,0.447758,0.497466,0.031834,17.635091,0.087186,10418.697183,0.857995
min,1.000000,1.000000,1.000000,0.000000,18.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000
25%,24152.000000,4.000000,4.000000,0.000000,34.000000,8.000000,123.000000,0.000000,5.584960e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.170000
50%,48303.000000,7.000000,7.000000,1.000000,41.000000,14.000000,146.000000,0.000000,8.090000e+05,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,72454.000000,10.000000,10.000000,1.000000,50.000000,19.000000,171.000000,1.000000,1.163900e+06,1.000000,1.000000,0.000000,0.000000,0.000000,10000.000000,0.050000
max,96605.000000,12.000000,12.000000,1.000000,86.000000,2015.000000,2000.000000,1.000000,9.449000e+06,1.000000,1.000000,1.000000,737.000000,1.000000,120873.000000,60.020000

In [19]:
# at some observations driving experience representing first driving year
df['POLICY_MIN_DRIVING_EXPERIENCE'].sort_values(ascending=False).head(5)

77054    2015
81784    2015
34508    2015
28989    2015
79872    2014
Name: POLICY_MIN_DRIVING_EXPERIENCE, dtype: int64

In [20]:
df['POLICY_MIN_DRIVING_EXPERIENCE'] = [2021 - x if x > 1900 else x for x in df['POLICY_MIN_DRIVING_EXPERIENCE']]
df['POLICY_MIN_DRIVING_EXPERIENCE'].describe()

count    96605.000000
mean        14.678712
std          9.289444
min          0.000000
25%          8.000000
50%         14.000000
75%         19.000000
max         65.000000
Name: POLICY_MIN_DRIVING_EXPERIENCE, dtype: float64

In [21]:
# engine hp can't be 0 or more than ~700
df = df.drop(df[(df['VEHICLE_ENGINE_POWER']>700) | (df['VEHICLE_ENGINE_POWER']<=0)].index)
df['VEHICLE_ENGINE_POWER'].sort_values(ascending=False)

46982    626.0
59862    585.0
75779    585.0
20484    585.0
16807    580.0
         ...
62066     51.0
21805     51.0
78158     51.0
17205     51.0
15924     51.0
Name: VEHICLE_ENGINE_POWER, Length: 96586, dtype: float64

In [22]:
# insurance sum can't be 0
df = df.drop(df[df['VEHICLE_SUM_INSURED']<=0].index)
df['VEHICLE_SUM_INSURED'].describe()

count    9.654400e+04
mean     9.810795e+05
std      6.899739e+05
min      2.323000e+04
25%      5.588978e+05
50%      8.091940e+05
75%      1.163990e+06
max      9.449000e+06
Name: VEHICLE_SUM_INSURED, dtype: float64

In [23]:
# drop bad POLICY_CLM_N
df = df.drop(index=df[df['POLICY_CLM_N'] == 'n/d'].index)

In [24]:
# drop bad POLICY_YEARS_RENEWED_N
df = df.drop(index=df[df['POLICY_YEARS_RENEWED_N'] == 'N'].index)

In [25]:
# cast POLICY_YEARS_RENEWED_N to integer 
df['POLICY_YEARS_RENEWED_N'] = pd.to_numeric(df['POLICY_YEARS_RENEWED_N'], downcast='integer')
df['POLICY_YEARS_RENEWED_N'].describe()

count    96488.000000
mean         1.495129
std          1.601984
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max         10.000000
Name: POLICY_YEARS_RENEWED_N, dtype: float64

In [26]:
df = df.drop_duplicates()
df.shape

(96488, 30)

In [27]:
bad = ['POLICY_ID', 'POLICY_END_MONTH', 'POLICY_INTERMEDIARY']

df = df.drop(bad, axis=1)
df.to_csv('clean_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 96488 entries, 0 to 96604
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   DATA_TYPE                      96488 non-null  object
 1   POLICY_BEGIN_MONTH             96488 non-null  int64
 2   POLICY_IS_RENEWED              96488 non-null  int64
 3   POLICY_SALES_CHANNEL           96488 non-null  object
 4   POLICY_SALES_CHANNEL_GROUP     96488 non-null  object
 5   POLICY_BRANCH                  96488 non-null  object
 6   POLICY_MIN_AGE                 96488 non-null  int64
 7   POLICY_MIN_DRIVING_EXPERIENCE  96488 non-null  int64
 8   VEHICLE_MAKE                   96488 non-null  object
 9   VEHICLE_MODEL                  96488 non-null  object
 10  VEHICLE_ENGINE_POWER           96488 non-null  float64
 11  VEHICLE_IN_CREDIT              96488 non-null  int64
 12  VEHICLE_SUM_INSURED            96488 non-null  float64
 13  INSURER_GENDER                 96488 non-null  object
 14  POLICY_CLM_N                   96488 non-null  object
 15  POLICY_CLM_GLT_N               96488 non-null  object
 16  POLICY_PRV_CLM_N               96488 non-null  object
 17  POLICY_PRV_CLM_GLT_N           96488 non-null  object
 18  CLIENT_HAS_DAGO                96488 non-null  int64
 19  CLIENT_HAS_OSAGO               96488 non-null  int64
 20  POLICY_COURT_SIGN              96488 non-null  int64
 21  CLAIM_AVG_ACC_ST_PRD           96488 non-null  float64
 22  POLICY_HAS_COMPLAINTS          96488 non-null  int64
 23  POLICY_YEARS_RENEWED_N         96488 non-null  int8
 24  POLICY_DEDUCT_VALUE            96488 non-null  float64
 25  CLIENT_REGISTRATION_REGION     96488 non-null  object
 26  POLICY_PRICE_CHANGE            96488 non-null  float64
dtypes: float64(5), int64(9), int8(1), object(12)
memory usage: 20.0+ MB

In [28]:
encoded_df = pd.concat([pd.get_dummies(df[for_encoding]), df.drop(for_encoding, axis=1)], axis=1)
encoded_df.shape

(96488, 344)

In [29]:
encoded_df.to_csv('encoded_data.csv')